name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.2

    - name: Build amd64
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags " -X 'main.GoVersion=$(go version)' -X main.GitCommit=$(git rev-parse HEAD) -X 'main.BuildTime=$(date +"%Y-%m-%d %H:%M:%S")'" -o China_Telecom_Monitor_amd64 ./cmd/main.go

    - name: Build arm64
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags " -X 'main.GoVersion=$(go version)' -X main.GitCommit=$(git rev-parse HEAD) -X 'main.BuildTime=$(date +"%Y-%m-%d %H:%M:%S")'" -o China_Telecom_Monitor_arm64 ./cmd/main.go

    - name: Deliver amd64 bin
      uses: actions/upload-artifact@v4
      with:
        name: China_Telecom_Monitor_amd64
        path: China_Telecom_Monitor_amd64
        retention-days: 30

    - name: Deliver arm64 bin
      uses: actions/upload-artifact@v4
      with:
        name: China_Telecom_Monitor_arm64
        path: China_Telecom_Monitor_arm64
        retention-days: 30